name: Github Release Notes 2

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  github-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Generate release notes
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
